# package.yml
package:
  name: 'yf-package-example' # No capitalization
  description: 'An example package for yflat'
  version: 0.1.0
  url: 'https://github.com/JakeRoggenbuck/yf-package-example'

  authors: # Optional
    - 'Jake Roggenbuck'

  license: 'MIT' # Optional

# Dependencies for this package
depends:
